SideBar component
gdsc-nits-org/guidance-grid pull request #12
Opened 2022-12-01 17:27 UTC by kherkatary

2022-12-02 18:52 UTC, resyfer requested changes

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.jsx
> +  const tagspan = tags.map((tag) => <span>{tag}</span>);
Even though this is technically allowed, try to always use JSX inside the return statement (where JSX is supposed to be), as this is prone to recalculating the map.

Place this directly inside JSX.

Also, always use a key with a map. A [good reference from docs](https://reactjs.org/docs/lists-and-keys.html)

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.jsx
> +        <p>What is ReactJS and how can it be used int development</p>
Convert these bookmarks into links, as well as using a map to iterate over an array of bookmarks. Also, just take the first 5 of them from the array (keep more than 5 elements in the array to check).

This is done as mostly your backend data may contain all of the bookmarks.

Also side tip: For dummy content, you can use [Lorem Ipsum](https://www.lipsum.com/) which is a standard for dummy text.

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.module.scss
> +  margin: 2rem auto 2rem auto;
you can shorten this to:
margin: 2rem auto;

the first applies to top and bottom, while second for left and right.

Also, decide on a common unit. You use rem here, and vh above, and % for width as well (which is a modified version of vw which takes scrollbar into account).

Use this unit (vh-vw combo, or rem), and keep it same in as many places as possible (*not* all, but *as many as possible*)

Don't use pixel except in media query condition.

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.module.scss
> +    border: 1.5px solid $border-color;
Same point about units.

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.module.scss
> +}
This block and the import above is not necessary as index.scss already has these lines, and it was not imported as a module (and hence applies to all pages).

**Always read the index.scss to see variables already defined**

Also, if you want to set a font, keep the name as a variable in index.scss, like --gdsc-font-1 (which already exists, and expands to Poppins)

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.module.scss
> +
An additional tip, you can [disable user's ability to select the text](https://www.w3schools.com/cssref/css3_pr_user-select.php), to make it more "button-like".

If you wish to implement it here, your choice.

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.module.scss
> +    margin-bottom: -10px;
Fix the unit issue in every occurence.

2022-12-02 18:52 UTC, resyfer commented on src/Pages/Home/Home.jsx
> +            return <ArticleCard data={item} id={index} key={item?.id} />;
For a single line return from an arrow function, [you don't need to write return](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#syntax)

2022-12-02 18:52 UTC, resyfer commented on src/Pages/Home/Home.module.scss
> +  .articlesection {
Always add an empty line to separate two style blocks (add this change wherever necessary)

2022-12-02 18:52 UTC, resyfer commented on src/Components/SideBar/SideBar.module.scss
> +.box1 {
Improve naming of classes. Variables should not be named box1, box2

2022-12-04 04:23 UTC, resyfer requested changes

2022-12-04 04:23 UTC, resyfer commented on src/Components/SideBar/SideBar.jsx
>          {tags.slice(0, 15).map((tag) => (
Add a key for map. *Always* add a key for the map.

2022-12-04 14:45 UTC, resyfer requested changes

2022-12-04 14:45 UTC, resyfer commented on src/Components/SideBar/SideBar.jsx
> +import sidebarData from "./sidebarData.json";
Use the fetch hook made by @JDeepD. Ask him how to use it, understand how it was written, and import the data using the hook (ie. in essence, using fetch API)

2022-12-07 14:27 UTC, codadept approved these changes

2022-12-07 14:28 UTC, codadept approved these changes

2022-12-07 14:28 UTC, merged