ADD:SignIN and SignUp Pages
gdsc-nits-org/guidance-grid pull request #43
Opened 2023-05-21 06:01 UTC by BIPS8812

2023-06-12 18:16 UTC, codadept requested changes

2023-06-12 18:16 UTC, codadept commented on src/Components/SignInForm/SignInForm.module.scss
> +
Import the font in index.scss and create a css variable and then use it in required files

2023-06-12 18:16 UTC, codadept commented on src/Components/SignUpForm/SignUpForm.module.scss
> +
See you have imported the font twice. REDUNDANT. Use the suggested approach

2023-06-12 18:16 UTC, codadept commented on src/Components/SignUpForm/SignUpForm.module.scss
> +        font-family: "Poppins";
Use the variable defined in index.scss. Always use variables. Check for all the scss files you have written

2023-06-12 18:16 UTC, codadept commented on src/Pages/SignIn/SignIn.module.scss
> +
Fix this too

2023-06-12 18:16 UTC, codadept commented on src/Pages/SignUp/SignUp.module.scss
> +@import url('https://fonts.googleapis.com/css2?family=Noto+Sans:wght@500&display=swap');
This too

2023-06-16 21:02 UTC, JDeepD commented on src/Pages/SignUp/SignUp.jsx
> -      <div className={style.gdsc}>
Since Footer is now present, This portion is no longer required.

2023-06-16 21:04 UTC, JDeepD commented
The Navbar is present and still has all the nav-items that should be accessible to only authenticated user. This will be removed in the Auth Integration PR

2023-06-29 14:00 UTC, merged